# Wprowadzenie do sztucznej inteligencji i uczenia maszynowego

### Ćwiczenia 3. — Zadania.

---

#### Zaimportuj biblioteki numpy i pandas.

In [2]:
import numpy as np
import pandas as pd

#### Załaduj plik csv.
***
Do zmiennej `df` załaduj plik `cars.csv`.

In [3]:
df = pd.read_csv("cars.csv")

#### Wyświetl pierwsze 5 linijek obiektu ''df''.

In [4]:
df.head()

,manufacturer_name,model_name,transmission,color,odometer_value,year_produced,engine_fuel,engine_has_gas,engine_type,engine_capacity,...,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,duration_listed
0,Subaru,Outback,automatic,silver,190000,2010,gasoline,False,gasoline,2.5,...,True,True,True,False,True,False,True,True,True,16
1,Subaru,Outback,automatic,blue,290000,2002,gasoline,False,gasoline,3.0,...,True,False,False,True,True,False,False,False,True,83
2,Subaru,Forester,automatic,red,402000,2001,gasoline,False,gasoline,2.5,...,True,False,False,False,False,False,False,True,True,151
3,Subaru,Impreza,mechanical,blue,10000,1999,gasoline,False,gasoline,3.0,...,False,False,False,False,False,False,False,False,False,86
4,Subaru,Legacy,automatic,black,280000,2001,gasoline,False,gasoline,2.5,...,True,False,True,True,False,False,False,False,True,7

#### Sprawdź, które kolumny zamienić na typ 'category'.
***
Kolumny, w których wartości przyjmują tylko kilka różnych parametrów, warto zamienić typ na `'category'`.
Zwróć listę kolumn, które są typu `'object'` i przyjmują mniej niż 20 różnych wartości.

In [5]:
df_unique = df.loc[:, df.nunique() < 20]
df_unique = df_unique.astype("category")
df_unique.dtypes

transmission       category
color              category
engine_fuel        category
engine_has_gas     category
engine_type        category
body_type          category
has_warranty       category
state              category
drivetrain         category
is_exchangeable    category
location_region    category
feature_0          category
feature_1          category
feature_2          category
feature_3          category
feature_4          category
feature_5          category
feature_6          category
feature_7          category
feature_8          category
feature_9          category
dtype: object

#### Napisz funkcję, która nadaje kolumnom typ 'category'.
***
Funkcja jako argumenty będzie przyjmować obiekt Dataframe oraz listę z nazwami kolumn, którym chcielibyśmy zmienić typ na `category`.

In [6]:
list_of_columns = ['transmission', 'color', 'engine_fuel', 'engine_type', 'body_type', 'state', 'drivetrain', 'location_region']

In [7]:
def proper_columns_types(df, list_of_columns):
    for col in list_of_columns:
        df[col]=df[col].astype("category")
    return df

In [8]:
df = proper_columns_types(df, list_of_columns)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38531 entries, 0 to 38530
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   manufacturer_name  38531 non-null  object
 1   model_name         38531 non-null  object
 2   transmission       38531 non-null  category
 3   color              38531 non-null  category
 4   odometer_value     38531 non-null  int64
 5   year_produced      38531 non-null  int64
 6   engine_fuel        38531 non-null  category
 7   engine_has_gas     38531 non-null  bool
 8   engine_type        38531 non-null  category
 9   engine_capacity    38521 non-null  float64
 10  body_type          38531 non-null  category
 11  has_warranty       38531 non-null  bool
 12  state              38531 non-null  category
 13  drivetrain         38531 non-null  category
 14  price_usd          38531 non-null  float64
 15  is_exchangeable    38531 non-null  bool
 16  location_region    38531 non-null  category
 17  number_of_photos   38531 non-null  int64
 18  up_counter         38531 non-null  int64
 19  feature_0          38531 non-null  bool
 20  feature_1          38531 non-null  bool
 21  feature_2          38531 non-null  bool
 22  feature_3          38531 non-null  bool
 23  feature_4          38531 non-null  bool
 24  feature_5          38531 non-null  bool
 25  feature_6          38531 non-null  bool
 26  feature_7          38531 non-null  bool
 27  feature_8          38531 non-null  bool
 28  feature_9          38531 non-null  bool
 29  duration_listed    38531 non-null  int64
dtypes: bool(13), category(8), float64(2), int64(5), object(2)
memory usage: 3.4+ MB

#### Wczytaj plik i od razu nadaj odpowiednim kolumnom typ 'category'.

In [19]:
x={col: "category" for col in list_of_columns}
print (x)
df = pd.read_csv("cars.csv", dtype = x)
df.dtypes

{'transmission': 'category', 'color': 'category', 'engine_fuel': 'category', 'engine_type': 'category', 'body_type': 'category', 'state': 'category', 'drivetrain': 'category', 'location_region': 'category'}

manufacturer_name      object
model_name             object
transmission         category
color                category
odometer_value          int64
year_produced           int64
engine_fuel          category
engine_has_gas           bool
engine_type          category
engine_capacity       float64
body_type            category
has_warranty             bool
state                category
drivetrain           category
price_usd             float64
is_exchangeable          bool
location_region      category
number_of_photos        int64
up_counter              int64
feature_0                bool
feature_1                bool
feature_2                bool
feature_3                bool
feature_4                bool
feature_5                bool
feature_6                bool
feature_7                bool
feature_8                bool
feature_9                bool
duration_listed         int64
dtype: object

#### Napisz funkcję, która printuje brakujące dane.
***
Funkcja ta jak argument ma przyjmować obiekt typu Dataframe i printować na ekran liczbę brakujących wartości dla każdej kolumny w podanym DataFrame.

In [20]:
def print_missing(df):
    print(df.isna().sum())

print_missing(df)

manufacturer_name     0
model_name            0
transmission          0
color                 0
odometer_value        0
year_produced         0
engine_fuel           0
engine_has_gas        0
engine_type           0
engine_capacity      10
body_type             0
has_warranty          0
state                 0
drivetrain            0
price_usd             0
is_exchangeable       0
location_region       0
number_of_photos      0
up_counter            0
feature_0             0
feature_1             0
feature_2             0
feature_3             0
feature_4             0
feature_5             0
feature_6             0
feature_7             0
feature_8             0
feature_9             0
duration_listed       0
dtype: int64

#### Napisz funkcję, która zamienia losowe dane na 'np.nan'.
***
W związku z tym, że chcemy nauczyć się pracować z brakującymi danymi, najpierw musimy takie stworzyć.

Nasza funkcja jako argumenty będzie przyjmować obiekt Dataframe oraz słownik. Kluczem w słowniku będą nazwy kolumn, a wartościami będą liczby błędów, które chcemy wprowadzić (`{'odometer_value': 7}` oznacza, że w kolumnie `'odometer_value'` chcemy zamienić 7 losowych wierszy na typ `'np.nan'`)

Podpowiedź:

W ten sposób możemy zmienić wartość na ` 'value'` w losowym wierszu w kolumnie `'column'`.

`df.loc[df.sample().index, column] = value`

In [14]:
error_dict = {'odometer_value': 7, 'duration_listed': 10, 'color': 6, 'engine_type': 2, 'price_usd': 4}

In [21]:
def introduce_nan(df, error_dict):  
    for column in error_dict:
        df.loc[df.sample(error_dict[column]).index, column] = np.nan
    return df

print_missing(df)

manufacturer_name     0
model_name            0
transmission          0
color                 0
odometer_value        0
year_produced         0
engine_fuel           0
engine_has_gas        0
engine_type           0
engine_capacity      10
body_type             0
has_warranty          0
state                 0
drivetrain            0
price_usd             0
is_exchangeable       0
location_region       0
number_of_photos      0
up_counter            0
feature_0             0
feature_1             0
feature_2             0
feature_3             0
feature_4             0
feature_5             0
feature_6             0
feature_7             0
feature_8             0
feature_9             0
duration_listed       0
dtype: int64

#### Wprowadź błędy do danych.
***
Użyj napisanej powyżej funkcji do wprowadzenia brakujących wartości do obiektu `'df_err'`.

Sprawdź, czy udało Ci się wprowadzić te błędy za pomocą funkcji do printowania brakujących wartości.

In [22]:
df_error = df.copy()

In [24]:
df_error = introduce_nan(df_error, error_dict)
print_missing(df_error)

manufacturer_name     0
model_name            0
transmission          0
color                12
odometer_value       14
year_produced         0
engine_fuel           0
engine_has_gas        0
engine_type           4
engine_capacity      10
body_type             0
has_warranty          0
state                 0
drivetrain            0
price_usd             8
is_exchangeable       0
location_region       0
number_of_photos      0
up_counter            0
feature_0             0
feature_1             0
feature_2             0
feature_3             0
feature_4             0
feature_5             0
feature_6             0
feature_7             0
feature_8             0
feature_9             0
duration_listed      20
dtype: int64

#### Zamień dane typu 'np.nan' na dane liczbowe.
***
W kolumnach `'odometer_value'` i `'duration_listed'` zamień brakujące wartości na średnią wartość całej kolumny.

W kolumnach `'color':` i `'engine_type'`: zamień brakujące wartości na najczęściej występujący element w całej kolumnie.

W kolumnie `'price_usd'` usuń brakujące wartości z naszego obiektu Dataframe.

In [29]:
df_err = df_error.copy()

In [31]:
print (print_missing(df_err))
print (df_err[["odometer_value" , "duration_listed"]].isna().sum())
df_err[["odometer_value" , "duration_listed"]]=df_err[["odometer_value" , "duration_listed"]].fillna(df_err[["odometer_value" , "duration_listed"]].mean())
print (df_err[["odometer_value" , "duration_listed"]].isna().sum())

manufacturer_name     0
model_name            0
transmission          0
color                12
odometer_value        0
year_produced         0
engine_fuel           0
engine_has_gas        0
engine_type           4
engine_capacity      10
body_type             0
has_warranty          0
state                 0
drivetrain            0
price_usd             8
is_exchangeable       0
location_region       0
number_of_photos      0
up_counter            0
feature_0             0
feature_1             0
feature_2             0
feature_3             0
feature_4             0
feature_5             0
feature_6             0
feature_7             0
feature_8             0
feature_9             0
duration_listed       0
dtype: int64
None
odometer_value     0
duration_listed    0
dtype: int64
odometer_value     0
duration_listed    0
dtype: int64

In [32]:
print (print_missing(df_err))
df_err[["color","engine_type"]]=df_err[["color","engine_type"]].fillna(df_err[["color","engine_type"]].mode().iloc[0])
print (print_missing(df_err))

manufacturer_name     0
model_name            0
transmission          0
color                12
odometer_value        0
year_produced         0
engine_fuel           0
engine_has_gas        0
engine_type           4
engine_capacity      10
body_type             0
has_warranty          0
state                 0
drivetrain            0
price_usd             8
is_exchangeable       0
location_region       0
number_of_photos      0
up_counter            0
feature_0             0
feature_1             0
feature_2             0
feature_3             0
feature_4             0
feature_5             0
feature_6             0
feature_7             0
feature_8             0
feature_9             0
duration_listed       0
dtype: int64
None
manufacturer_name     0
model_name            0
transmission          0
color                 0
odometer_value        0
year_produced         0
engine_fuel           0
engine_has_gas        0
engine_type           0
engine_capacity      10
body_type             0
has_warranty          0
state                 0
drivetrain            0
price_usd             8
is_exchangeable       0
location_region       0
number_of_photos      0
up_counter            0
feature_0             0
feature_1             0
feature_2             0
feature_3             0
feature_4             0
feature_5             0
feature_6             0
feature_7             0
feature_8             0
feature_9             0
duration_listed       0
dtype: int64
None

In [33]:
print (df_err.loc[df_err["price_usd"].isna(),"price_usd"])
df_err = df_err.dropna(subset=["price_usd"])
print (df_err.loc[df_err["price_usd"].isna(),"price_usd"])

3560    NaN
6070    NaN
11233   NaN
17289   NaN
23784   NaN
23811   NaN
27716   NaN
36029   NaN
Name: price_usd, dtype: float64
Series([], Name: price_usd, dtype: float64)

In [34]:
df.head()

,manufacturer_name,model_name,transmission,color,odometer_value,year_produced,engine_fuel,engine_has_gas,engine_type,engine_capacity,...,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,duration_listed
0,Subaru,Outback,automatic,silver,190000,2010,gasoline,False,gasoline,2.5,...,True,True,True,False,True,False,True,True,True,16
1,Subaru,Outback,automatic,blue,290000,2002,gasoline,False,gasoline,3.0,...,True,False,False,True,True,False,False,False,True,83
2,Subaru,Forester,automatic,red,402000,2001,gasoline,False,gasoline,2.5,...,True,False,False,False,False,False,False,True,True,151
3,Subaru,Impreza,mechanical,blue,10000,1999,gasoline,False,gasoline,3.0,...,False,False,False,False,False,False,False,False,False,86
4,Subaru,Legacy,automatic,black,280000,2001,gasoline,False,gasoline,2.5,...,True,False,True,True,False,False,False,False,True,7

#### Napisz funkcję, która zamienia dane typu 'np.nan' na dane liczbowe.
***
Nasza funkcja jako argumenty będzie przyjmować obiekt Dataframe oraz słownik. Kluczem w słowniku będą nazwy kolumn, a wartościami będą wartości `'average'`,`'max'` albo `'drop'` (w zależności co chcemy zrobić z brakującymi danymi).

In [35]:
replace_dict = {'odometer_value': 'average', 'duration_listed': 'average', 'color': 'max', 'engine_type': 'max', 'price_usd': 'drop'}

In [36]:
def replace_column(df, replace_dict):
    df[["odometer_value" , "duration_listed"]]=df[["odometer_value" , "duration_listed"]].fillna(df[["odometer_value" , "duration_listed"]].mean())
    df[["color","engine_type"]]=df[["color","engine_type"]].fillna(df[["color","engine_type"]].mode().iloc[0])
    df = df.dropna(subset=["price_usd"])
                                                                                                                    
    return df

#### Usuń błędy z danych.
***
Użyj napisanej powyżej funkcji do zastąpienia lub usunięcia brakujących wartości z obiektu `'df_err'`.

Sprawdź, czy udało Ci się to zrobić za pomocą funkcji do printowania brakujących wartości.

In [37]:
df_err = replace_column(df_err, replace_dict)
print_missing(df_err)

manufacturer_name     0
model_name            0
transmission          0
color                 0
odometer_value        0
year_produced         0
engine_fuel           0
engine_has_gas        0
engine_type           0
engine_capacity      10
body_type             0
has_warranty          0
state                 0
drivetrain            0
price_usd             0
is_exchangeable       0
location_region       0
number_of_photos      0
up_counter            0
feature_0             0
feature_1             0
feature_2             0
feature_3             0
feature_4             0
feature_5             0
feature_6             0
feature_7             0
feature_8             0
feature_9             0
duration_listed       0
dtype: int64

#### Napisz zapytanie.
***
Znajdź wszystkie samochody marki Mercedes-Benz wyprodukowane po 2010 roku.

In [43]:
df.head()
df.loc[df["year_produced"]>2010,["year_produced"]]

       year_produced
5               2011
14              2011
18              2014
19              2013
34              2011
...              ...
38262           2016
38339           2012
38350           2016
38367           2015
38435           2018

[7236 rows x 1 columns]

In [42]:
df[df["year_produced"]>2010]["year_produced"]

5        2011
14       2011
18       2014
19       2013
34       2011
         ...
38262    2016
38339    2012
38350    2016
38367    2015
38435    2018
Name: year_produced, Length: 7236, dtype: int64

#### Policz rok produkcji podniesiony do kwadratu.
***
W obiekcie `'df_sec'` stwórz nowe kolumny `'year_produced_squared_1'` i `'year_produced_squared_2'` w których znajdzie się rok produkcji podniesiony do kwadratu.

Zrób to na dwa sposoby:
- działanie bezpośrednio na kolumnie
- działanie przy pomocy funkcji `.apply(lambda x: x)`

In [49]:
df_sec = df.copy()
df_sec["year_produced_squared_1"] = df["year_produced"]**1
df_sec["year_produced_squared_2"] = df["year_produced"]**2
df_sec.head()

,manufacturer_name,model_name,transmission,color,odometer_value,year_produced,engine_fuel,engine_has_gas,engine_type,engine_capacity,...,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,duration_listed,year_produced_squared_1,year_produced_squared_2
0,Subaru,Outback,automatic,silver,190000,2010,gasoline,False,gasoline,2.5,...,True,False,True,False,True,True,True,16,2010,4040100
1,Subaru,Outback,automatic,blue,290000,2002,gasoline,False,gasoline,3.0,...,False,True,True,False,False,False,True,83,2002,4008004
2,Subaru,Forester,automatic,red,402000,2001,gasoline,False,gasoline,2.5,...,False,False,False,False,False,True,True,151,2001,4004001
3,Subaru,Impreza,mechanical,blue,10000,1999,gasoline,False,gasoline,3.0,...,False,False,False,False,False,False,False,86,1999,3996001
4,Subaru,Legacy,automatic,black,280000,2001,gasoline,False,gasoline,2.5,...,True,True,False,False,False,False,True,7,2001,4004001

In [48]:
df_sec["year_produced_squared_1"] = df["year_produced"].apply(lambda x:x*2)
df_sec["year_produced_squared_2"] = df["year_produced"].apply(lambda x:x**2)
df_sec

,manufacturer_name,model_name,transmission,color,odometer_value,year_produced,engine_fuel,engine_has_gas,engine_type,engine_capacity,...,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,duration_listed,year_produced_squared_1,year_produced_squared_2
0,Subaru,Outback,automatic,silver,190000,2010,gasoline,False,gasoline,2.5,...,True,False,True,False,True,True,True,16,4020,4040100
1,Subaru,Outback,automatic,blue,290000,2002,gasoline,False,gasoline,3.0,...,False,True,True,False,False,False,True,83,4004,4008004
2,Subaru,Forester,automatic,red,402000,2001,gasoline,False,gasoline,2.5,...,False,False,False,False,False,True,True,151,4002,4004001
3,Subaru,Impreza,mechanical,blue,10000,1999,gasoline,False,gasoline,3.0,...,False,False,False,False,False,False,False,86,3998,3996001
4,Subaru,Legacy,automatic,black,280000,2001,gasoline,False,gasoline,2.5,...,True,True,False,False,False,False,True,7,4002,4004001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38526,Chrysler,300,automatic,silver,290000,2000,gasoline,False,gasoline,3.5,...,False,True,True,False,False,True,True,301,4000,4000000
38527,Chrysler,PT Cruiser,mechanical,blue,321000,2004,diesel,False,diesel,2.2,...,False,True,True,False,False,True,True,317,4008,4016016
38528,Chrysler,300,automatic,blue,777957,2000,gasoline,False,gasoline,3.5,...,False,True,True,False,False,True,True,369,4000,4000000
38529,Chrysler,PT Cruiser,mechanical,black,20000,2001,gasoline,False,gasoline,2.0,...,False,False,False,False,False,False,True,490,4002,4004001
38530,Chrysler,Voyager,automatic,silver,297729,2000,gasoline,False,gasoline,2.4,...,False,False,False,False,False,False,True,632,4000,4000000

#### Oceń czy samochód można uznać za nowy.
***
W obiekcie `'df_sec'` stwórz nową kolumnę `'is_new'`. Wartość powinna wynosić `True` dla wszystkich samochodów wyprodukowanych po 2016 i z przebiegiem mniejszym niż 100 000 km (oba warunki spełnione jednocześnie). W pozostałych przypadkach wartość powinna wynosić `'False'`.

In [60]:
df_sec["is_new"] = (df_sec["year_produced"] > 2016) & (df_sec["odometer_value"] < 100000)

df_sec.loc[df_sec["is_new"]==True,"is_new"]

119      True
220      True
291      True
293      True
294      True
         ...
35179    True
35301    True
35516    True
36884    True
38435    True
Name: is_new, Length: 1112, dtype: bool

#### Policz średnią liczbę przebytych kilometrów na rok.
***
W obiekcie `'df_sec'` stwórz nową kolumnę `'km_per_year'`. Wartość powinna wynosić liczbę przebytych kilometrów podzieloną na lata użytkowania (zakładamy, że dane pochodzą z 2019 roku).

In [64]:
df_sec["km_per_year"]=df_sec["odometer_value"]/(2019-df_sec["year_produced"])
df_sec

,manufacturer_name,model_name,transmission,color,odometer_value,year_produced,engine_fuel,engine_has_gas,engine_type,engine_capacity,...,feature_5,feature_6,feature_7,feature_8,feature_9,duration_listed,year_produced_squared_1,year_produced_squared_2,is_new,km_per_year
0,Subaru,Outback,automatic,silver,190000,2010,gasoline,False,gasoline,2.5,...,True,False,True,True,True,16,2010,4040100,False,21111.111111
1,Subaru,Outback,automatic,blue,290000,2002,gasoline,False,gasoline,3.0,...,True,False,False,False,True,83,2002,4008004,False,17058.823529
2,Subaru,Forester,automatic,red,402000,2001,gasoline,False,gasoline,2.5,...,False,False,False,True,True,151,2001,4004001,False,22333.333333
3,Subaru,Impreza,mechanical,blue,10000,1999,gasoline,False,gasoline,3.0,...,False,False,False,False,False,86,1999,3996001,False,500.000000
4,Subaru,Legacy,automatic,black,280000,2001,gasoline,False,gasoline,2.5,...,False,False,False,False,True,7,2001,4004001,False,15555.555556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38526,Chrysler,300,automatic,silver,290000,2000,gasoline,False,gasoline,3.5,...,True,False,False,True,True,301,2000,4000000,False,15263.157895
38527,Chrysler,PT Cruiser,mechanical,blue,321000,2004,diesel,False,diesel,2.2,...,True,False,False,True,True,317,2004,4016016,False,21400.000000
38528,Chrysler,300,automatic,blue,777957,2000,gasoline,False,gasoline,3.5,...,True,False,False,True,True,369,2000,4000000,False,40945.105263
38529,Chrysler,PT Cruiser,mechanical,black,20000,2001,gasoline,False,gasoline,2.0,...,False,False,False,False,True,490,2001,4004001,False,1111.111111
38530,Chrysler,Voyager,automatic,silver,297729,2000,gasoline,False,gasoline,2.4,...,False,False,False,False,True,632,2000,4000000,False,15669.947368

#### Napisz funkcję, która liczy przebyte kilometry w ciągu roku.
***
Nasza funkcja jako argumenty będzie przyjmować obiekt Dataframe oraz rok, z którego pochodzą dane.
Funkcja będzie zwracać obiekt typu Dataframe, który w kolumnie `'kpy'` ma policzoną tę wartość.

In [66]:
def calculate_kpy(df, year):
    df["km_per_year"]=df["odometer_value"]/(year-df["year_produced"])
    return df

#### Jeszcze raz policz średnią liczbę przebytych kilometrów na rok.
***
Na obiekcie `'df_sec'` użyj napisanej powyżej funkcji (zakładamy, że dane pochodzą z 2019 roku).

In [68]:
df_sec = calculate_kpy(df_sec, 2019)
df_sec

,manufacturer_name,model_name,transmission,color,odometer_value,year_produced,engine_fuel,engine_has_gas,engine_type,engine_capacity,...,feature_5,feature_6,feature_7,feature_8,feature_9,duration_listed,year_produced_squared_1,year_produced_squared_2,is_new,km_per_year
0,Subaru,Outback,automatic,silver,190000,2010,gasoline,False,gasoline,2.5,...,True,False,True,True,True,16,2010,4040100,False,21111.111111
1,Subaru,Outback,automatic,blue,290000,2002,gasoline,False,gasoline,3.0,...,True,False,False,False,True,83,2002,4008004,False,17058.823529
2,Subaru,Forester,automatic,red,402000,2001,gasoline,False,gasoline,2.5,...,False,False,False,True,True,151,2001,4004001,False,22333.333333
3,Subaru,Impreza,mechanical,blue,10000,1999,gasoline,False,gasoline,3.0,...,False,False,False,False,False,86,1999,3996001,False,500.000000
4,Subaru,Legacy,automatic,black,280000,2001,gasoline,False,gasoline,2.5,...,False,False,False,False,True,7,2001,4004001,False,15555.555556
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38526,Chrysler,300,automatic,silver,290000,2000,gasoline,False,gasoline,3.5,...,True,False,False,True,True,301,2000,4000000,False,15263.157895
38527,Chrysler,PT Cruiser,mechanical,blue,321000,2004,diesel,False,diesel,2.2,...,True,False,False,True,True,317,2004,4016016,False,21400.000000
38528,Chrysler,300,automatic,blue,777957,2000,gasoline,False,gasoline,3.5,...,True,False,False,True,True,369,2000,4000000,False,40945.105263
38529,Chrysler,PT Cruiser,mechanical,black,20000,2001,gasoline,False,gasoline,2.0,...,False,False,False,False,True,490,2001,4004001,False,1111.111111
38530,Chrysler,Voyager,automatic,silver,297729,2000,gasoline,False,gasoline,2.4,...,False,False,False,False,True,632,2000,4000000,False,15669.947368

#### Ustandaryzuj dane.
***
W obiekcie `'df_sec'` stwórz nowe kolumny `'odometer_value_min_max_norm'` i `'odometer_value_norm_dist_norm'` w których ustandaryzowana (znormalizowana) wartość z kolumny `'odometer_value'`.

Zrób to na dwa sposoby:
- standaryzacja z użyciem wartości minimalnych i maksymalnych
- standaryzacja z użyciem wartości średniej i odchylenia standardowego

In [71]:
mean_duration = df['odometer_value'].mean()
std_duration = df['odometer_value'].std()
df_sec["odometer_value_min_max_norm"]=(df['odometer_value'] - mean_duration) / std_duration
df_sec

,manufacturer_name,model_name,transmission,color,odometer_value,year_produced,engine_fuel,engine_has_gas,engine_type,engine_capacity,...,feature_7,feature_8,feature_9,duration_listed,year_produced_squared_1,year_produced_squared_2,is_new,km_per_year,odometer_value_min_max_norm,odometer_value_norm_dist_norm
0,Subaru,Outback,automatic,silver,190000,2010,gasoline,False,gasoline,2.5,...,True,True,True,16,2010,4040100,False,21111.111111,-0.432598,0.190000
1,Subaru,Outback,automatic,blue,290000,2002,gasoline,False,gasoline,3.0,...,False,False,True,83,2002,4008004,False,17058.823529,0.302305,0.290000
2,Subaru,Forester,automatic,red,402000,2001,gasoline,False,gasoline,2.5,...,False,True,True,151,2001,4004001,False,22333.333333,1.125396,0.402000
3,Subaru,Impreza,mechanical,blue,10000,1999,gasoline,False,gasoline,3.0,...,False,False,False,86,1999,3996001,False,500.000000,-1.755423,0.010000
4,Subaru,Legacy,automatic,black,280000,2001,gasoline,False,gasoline,2.5,...,False,False,True,7,2001,4004001,False,15555.555556,0.228815,0.280000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38526,Chrysler,300,automatic,silver,290000,2000,gasoline,False,gasoline,3.5,...,False,True,True,301,2000,4000000,False,15263.157895,0.302305,0.290000
38527,Chrysler,PT Cruiser,mechanical,blue,321000,2004,diesel,False,diesel,2.2,...,False,True,True,317,2004,4016016,False,21400.000000,0.530125,0.321000
38528,Chrysler,300,automatic,blue,777957,2000,gasoline,False,gasoline,3.5,...,False,True,True,369,2000,4000000,False,40945.105263,3.888316,0.777957
38529,Chrysler,PT Cruiser,mechanical,black,20000,2001,gasoline,False,gasoline,2.0,...,False,False,True,490,2001,4004001,False,1111.111111,-1.681933,0.020000
38530,Chrysler,Voyager,automatic,silver,297729,2000,gasoline,False,gasoline,2.4,...,False,False,True,632,2000,4000000,False,15669.947368,0.359106,0.297729

In [72]:
min_year = df['odometer_value'].min()
max_year = df['odometer_value'].max()
df_sec["odometer_value_norm_dist_norm"]=(df['odometer_value'] - min_year) / (max_year - min_year)
df_sec

,manufacturer_name,model_name,transmission,color,odometer_value,year_produced,engine_fuel,engine_has_gas,engine_type,engine_capacity,...,feature_7,feature_8,feature_9,duration_listed,year_produced_squared_1,year_produced_squared_2,is_new,km_per_year,odometer_value_min_max_norm,odometer_value_norm_dist_norm
0,Subaru,Outback,automatic,silver,190000,2010,gasoline,False,gasoline,2.5,...,True,True,True,16,2010,4040100,False,21111.111111,-0.432598,0.190000
1,Subaru,Outback,automatic,blue,290000,2002,gasoline,False,gasoline,3.0,...,False,False,True,83,2002,4008004,False,17058.823529,0.302305,0.290000
2,Subaru,Forester,automatic,red,402000,2001,gasoline,False,gasoline,2.5,...,False,True,True,151,2001,4004001,False,22333.333333,1.125396,0.402000
3,Subaru,Impreza,mechanical,blue,10000,1999,gasoline,False,gasoline,3.0,...,False,False,False,86,1999,3996001,False,500.000000,-1.755423,0.010000
4,Subaru,Legacy,automatic,black,280000,2001,gasoline,False,gasoline,2.5,...,False,False,True,7,2001,4004001,False,15555.555556,0.228815,0.280000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38526,Chrysler,300,automatic,silver,290000,2000,gasoline,False,gasoline,3.5,...,False,True,True,301,2000,4000000,False,15263.157895,0.302305,0.290000
38527,Chrysler,PT Cruiser,mechanical,blue,321000,2004,diesel,False,diesel,2.2,...,False,True,True,317,2004,4016016,False,21400.000000,0.530125,0.321000
38528,Chrysler,300,automatic,blue,777957,2000,gasoline,False,gasoline,3.5,...,False,True,True,369,2000,4000000,False,40945.105263,3.888316,0.777957
38529,Chrysler,PT Cruiser,mechanical,black,20000,2001,gasoline,False,gasoline,2.0,...,False,False,True,490,2001,4004001,False,1111.111111,-1.681933,0.020000
38530,Chrysler,Voyager,automatic,silver,297729,2000,gasoline,False,gasoline,2.4,...,False,False,True,632,2000,4000000,False,15669.947368,0.359106,0.297729

#### Zmień wszystkie dane w kolumnie na małe litery.
***
W obiekcie `'df_sec'` stwórz nową kolumnę `'model_name_lower'`, która będzie zawierać wartości z kolumny `'model_name'`, ale ze wszystkimi wielkimi literami zmienionymi na małe.

In [75]:
df_sec["model_name_lower"]=df_sec["model_name"].str.lower()
df_sec

,manufacturer_name,model_name,transmission,color,odometer_value,year_produced,engine_fuel,engine_has_gas,engine_type,engine_capacity,...,feature_8,feature_9,duration_listed,year_produced_squared_1,year_produced_squared_2,is_new,km_per_year,odometer_value_min_max_norm,odometer_value_norm_dist_norm,model_name_lower
0,Subaru,Outback,automatic,silver,190000,2010,gasoline,False,gasoline,2.5,...,True,True,16,2010,4040100,False,21111.111111,-0.432598,0.190000,outback
1,Subaru,Outback,automatic,blue,290000,2002,gasoline,False,gasoline,3.0,...,False,True,83,2002,4008004,False,17058.823529,0.302305,0.290000,outback
2,Subaru,Forester,automatic,red,402000,2001,gasoline,False,gasoline,2.5,...,True,True,151,2001,4004001,False,22333.333333,1.125396,0.402000,forester
3,Subaru,Impreza,mechanical,blue,10000,1999,gasoline,False,gasoline,3.0,...,False,False,86,1999,3996001,False,500.000000,-1.755423,0.010000,impreza
4,Subaru,Legacy,automatic,black,280000,2001,gasoline,False,gasoline,2.5,...,False,True,7,2001,4004001,False,15555.555556,0.228815,0.280000,legacy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38526,Chrysler,300,automatic,silver,290000,2000,gasoline,False,gasoline,3.5,...,True,True,301,2000,4000000,False,15263.157895,0.302305,0.290000,300
38527,Chrysler,PT Cruiser,mechanical,blue,321000,2004,diesel,False,diesel,2.2,...,True,True,317,2004,4016016,False,21400.000000,0.530125,0.321000,pt cruiser
38528,Chrysler,300,automatic,blue,777957,2000,gasoline,False,gasoline,3.5,...,True,True,369,2000,4000000,False,40945.105263,3.888316,0.777957,300
38529,Chrysler,PT Cruiser,mechanical,black,20000,2001,gasoline,False,gasoline,2.0,...,False,True,490,2001,4004001,False,1111.111111,-1.681933,0.020000,pt cruiser
38530,Chrysler,Voyager,automatic,silver,297729,2000,gasoline,False,gasoline,2.4,...,False,True,632,2000,4000000,False,15669.947368,0.359106,0.297729,voyager

#### Zmień nazwy kolumn.
***
W obiekcie `'df_sec'` zmień nazwy kolumn `'manufacturer_name'` oraz `'model_name'` na odpowiednio `'Manufacturer_Name'` i `'Model_Name'`.

In [76]:
changed_names_dict = {'manufacturer_name':'Manufacturer_Name', 'model_name':'Model_Name'}

In [80]:
df_sec = df_sec.rename(columns=changed_names_dict)
df_sec

,Manufacturer_Name,Model_Name,transmission,color,odometer_value,year_produced,engine_fuel,engine_has_gas,engine_type,engine_capacity,...,feature_8,feature_9,duration_listed,year_produced_squared_1,year_produced_squared_2,is_new,km_per_year,odometer_value_min_max_norm,odometer_value_norm_dist_norm,model_name_lower
0,Subaru,Outback,automatic,silver,190000,2010,gasoline,False,gasoline,2.5,...,True,True,16,2010,4040100,False,21111.111111,-0.432598,0.190000,outback
1,Subaru,Outback,automatic,blue,290000,2002,gasoline,False,gasoline,3.0,...,False,True,83,2002,4008004,False,17058.823529,0.302305,0.290000,outback
2,Subaru,Forester,automatic,red,402000,2001,gasoline,False,gasoline,2.5,...,True,True,151,2001,4004001,False,22333.333333,1.125396,0.402000,forester
3,Subaru,Impreza,mechanical,blue,10000,1999,gasoline,False,gasoline,3.0,...,False,False,86,1999,3996001,False,500.000000,-1.755423,0.010000,impreza
4,Subaru,Legacy,automatic,black,280000,2001,gasoline,False,gasoline,2.5,...,False,True,7,2001,4004001,False,15555.555556,0.228815,0.280000,legacy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38526,Chrysler,300,automatic,silver,290000,2000,gasoline,False,gasoline,3.5,...,True,True,301,2000,4000000,False,15263.157895,0.302305,0.290000,300
38527,Chrysler,PT Cruiser,mechanical,blue,321000,2004,diesel,False,diesel,2.2,...,True,True,317,2004,4016016,False,21400.000000,0.530125,0.321000,pt cruiser
38528,Chrysler,300,automatic,blue,777957,2000,gasoline,False,gasoline,3.5,...,True,True,369,2000,4000000,False,40945.105263,3.888316,0.777957,300
38529,Chrysler,PT Cruiser,mechanical,black,20000,2001,gasoline,False,gasoline,2.0,...,False,True,490,2001,4004001,False,1111.111111,-1.681933,0.020000,pt cruiser
38530,Chrysler,Voyager,automatic,silver,297729,2000,gasoline,False,gasoline,2.4,...,False,True,632,2000,4000000,False,15669.947368,0.359106,0.297729,voyager

#### Policz średnią wartość odczytu z licznika w zależności od marki i modelu samochodu.
***
Pogrupuj dane po kolumnach `'Manufacturer_Name'` oraz `'Model_Name'` i policz dla nich średnią z kolumny `'odometer_value'`.

In [81]:
df_sec.groupby(["Manufacturer_Name","Model_Name"]).agg({"odometer_value":"mean"})

                              odometer_value
Manufacturer_Name Model_Name
Acura             CL           220000.000000
                  ILX           78333.333333
                  Integra      218871.000000
                  MDX          199561.380952
                  RDX          148056.250000
...                                      ...
УАЗ               451          111660.500000
                  452          231586.750000
                  469          133524.882353
                  Hunter        86666.600000
                  Patriot      104476.533333

[1157 rows x 1 columns]

#### Policz średnią wartość pojemności silnika w zależności od typu skrzyni biegów i liczbę wystąpień danych typów skrzyni biegów.
***
Pogrupuj dane po kolumnie `'transmission'` i policz dla nich średnią z kolumny `'engine_capacity'` oraz policz liczbę obserwacji w każdej grupie.

In [84]:
df_sec.groupby(["transmission"]).agg({"engine_capacity":"mean","transmission": "count"})

/tmp/ipykernel_3829/3276945495.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_sec.groupby(["transmission"]).agg({"engine_capacity":"mean","transmission": "count"})

              engine_capacity  transmission
transmission
automatic            2.460844         12898
mechanical           1.851188         25633