# <span style="color:#0f766e; font-weight:700;">Analiza Danych (Python) - Lekcja 4</span>

1. [Mini-projekt: czyszczenie i analiza](#1.-Mini-projekt:-czyszczenie-i-analiza)
2. [Zadania projektowe](#2.-Zadania-projektowe)

# <span style="color:#0f766e; font-weight:700;">1. Mini-projekt: czyszczenie i analiza</span>

## <span style="color:#0f766e; font-weight:700;">Pliki</span>

- `dane/dane_lekcja3/participants_dirty.csv`
- `dane/dane_lekcja3/trials_dirty.csv`
- `dane/dane_lekcja3/city_reference.csv`
- `dane/dane_lekcja3/project_questions.json`

# <span style="color:#0f766e; font-weight:700;">2. Zadania projektowe</span>

## <span style="color:#0f766e; font-weight:700;">Zadanie 1</span>

Wczytaj wszystkie pliki projektu i sprawdź podstawowe informacje o tabelach (wymiary, typy, braki).

Wymagane biblioteki:
- `pandas`
- `json`

Wymagane funkcje/parametry:
- `pd.read_csv()`
- `json.load()` / `json.loads()`
- `DataFrame.shape`
- `DataFrame.info()`
- `DataFrame.isna()`
- `DataFrame.sum()`

In [ ]:
import json
import pandas as pd
from IPython.display import display

city_df = pd.read_csv("dane/dane_lekcja3/city_reference.csv")
participants_df = pd.read_csv("dane/dane_lekcja3/participants_dirty.csv")
trials_df = pd.read_csv("dane/dane_lekcja3/trials_dirty.csv")

with open("dane/dane_lekcja3/project_questions.json", "r", encoding="utf-8") as f:
    questions = json.load(f)
    
display(city_df.head())
display(participants_df.head())
display(trials_df.head())

       city         region  population_k
0  Warszawa    mazowieckie          1861
1    Krakow    malopolskie           806
2    Gdansk      pomorskie           487
3   Wroclaw   dolnoslaskie           674
4    Poznan  wielkopolskie           545

   participant_id   age     gender            group education sleep_hours stress_level reaction_time_ms memory_score attention_score session_date      city
0             707  30.0    kobieta  eksperymentalna       mgr         7.5            8            597.3          NaN            59,4   2025-11-10    Gdansk
1             975  19.0  mezczyzna        Kontrolna       mgr         5.6            3            565,4         65.7            57.6   08-11-2025  Szczecin
2             282  34.0          F  EKSPERYMENTALNA  doktorat         4.0            8            628,3         70,8            71.0   06-11-2025    Krakow
3             387  20.0          K        kontrolna       lic         7.3            5            562,2         83,0            64.7   31-10-2025    Lublin
4             262  33.0          K  eksperymentalna       mgr         8.2            1            630.5         82.9            91,6   2025-10-19    Gdansk

   trial_id  participant_id condition difficulty correct  rt_ms confidence_1_5
0         1             399         b       easy       1  458.0              1
1         2              19         a       easy       1  414.1              5
2         3             993         C     MEDIUM     tak  405,3              3
3         4             160         B       easy     tak  479.8              1
4         5             650         C       hard       1  731.2              4

In [128]:
city_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   city          8 non-null      object
 1   region        8 non-null      object
 2   population_k  8 non-null      int64
dtypes: int64(1), object(2)
memory usage: 320.0+ bytes

In [134]:
display(city_df.isna())

display(city_df.isna().sum())

display(city_df.shape)

    city  region  population_k
0  False   False         False
1  False   False         False
2  False   False         False
3  False   False         False
4  False   False         False
5  False   False         False
6  False   False         False
7  False   False         False

city            0
region          0
population_k    0
dtype: int64

(8, 3)

## <span style="color:#0f766e; font-weight:700;">Zadanie 2</span>

Znormalizuj nazwy kategorii w kolumnach `group`, `gender`, `education`, `condition`, `difficulty` (wielkość liter, warianty tekstowe).

Wymagane biblioteki:
- `pandas`

Wymagane funkcje/parametry:
- `Series.str.lower()`
- `Series.str.strip()`
- `Series.replace()`
- `Series.map()`
- `Series.value_counts()`

In [67]:
participants_df.head()

,participant_id,age,gender,group,education,sleep_hours,stress_level,reaction_time_ms,memory_score,attention_score,session_date,city
0,707,30.0,kobieta,eksperymentalna,mgr,7.5,8,597.3,NaN,"59,4",2025-11-10,Gdansk
1,975,19.0,mezczyzna,Kontrolna,mgr,5.6,3,"565,4",65.7,57.6,08-11-2025,Szczecin
2,282,34.0,F,EKSPERYMENTALNA,doktorat,4.0,8,"628,3","70,8",71.0,06-11-2025,Krakow
3,387,20.0,K,kontrolna,lic,7.3,5,"562,2","83,0",64.7,31-10-2025,Lublin
4,262,33.0,K,eksperymentalna,mgr,8.2,1,630.5,82.9,"91,6",2025-10-19,Gdansk

In [136]:
print (participants_df["group"].value_counts())
print (participants_df["gender"].value_counts())
print (participants_df["education"].value_counts())

group
kontrolna          364
eksperymentalna    354
Eksperymentalna     90
EKSPERYMENTALNA     78
KONTROLNA           76
Kontrolna           68
Name: count, dtype: int64
gender
mezczyzna    179
Male         179
F            172
K            171
M            170
kobieta      159
Name: count, dtype: int64
education
lic          189
licencjat    184
doktorat     171
mgr          171
magister     160
srednie      155
Name: count, dtype: int64

In [99]:
replacement_map = {
    "kontrolna": "kontrolna",
    "Kontrolna": "kontrolna",
    "KONTROLNA": "kontrolna",
    "eksperymentalna": "eksperymentalna",
    "Eksperymentalna": "eksperymentalna",
    "EKSPERYMENTALNA": "eksperymentalna",

    "kobieta": "kobieta",
    "K": "kobieta",
    "k": "kobieta",
    "mezczyzna": "mężczyzna",
    "M": "mężczyzna",
    "m": "mężczyzna",
    "Male": "mężczyzna",
    "male": "mężczyzna",
    "F": "kobieta",
    "f": "kobieta",

    "lic": "licencjat",
    "licencjat": "licencjat",
    "mgr": "magister",
    "magister": "magister",
    "doktorat": "doktorat",
    "srednie": "średnie",
    "średnie": "średnie"
}

In [111]:
participants_df.loc[:,["group", "gender", "education"]]

                group     gender  education
0     eksperymentalna    kobieta   magister
1           kontrolna  mężczyzna   magister
2     eksperymentalna    kobieta   doktorat
3           kontrolna    kobieta  licencjat
4     eksperymentalna    kobieta   magister
...               ...        ...        ...
1025  eksperymentalna  mężczyzna  licencjat
1026  eksperymentalna  mężczyzna  licencjat
1027  eksperymentalna    kobieta    średnie
1028        kontrolna    kobieta    średnie
1029        kontrolna    kobieta  licencjat

[1030 rows x 3 columns]

In [141]:
participants_df[["group", "gender", "education"]] = participants_df[["group", "gender", "education"]].apply(lambda x: x.str.lower().str.strip().replace(replacement_map))

participants_df.head()
print (participants_df["group"].value_counts())
print (participants_df["gender"].value_counts())
print (participants_df["education"].value_counts())

group
eksperymentalna    522
kontrolna          508
Name: count, dtype: int64
gender
mężczyzna    528
kobieta      502
Name: count, dtype: int64
education
licencjat    373
magister     331
doktorat     171
średnie      155
Name: count, dtype: int64

In [113]:
participants_df.head()

,participant_id,age,gender,group,education,sleep_hours,stress_level,reaction_time_ms,memory_score,attention_score,session_date,city
0,707,30.0,kobieta,eksperymentalna,magister,7.5,8,597.3,NaN,"59,4",2025-11-10,Gdansk
1,975,19.0,mężczyzna,kontrolna,magister,5.6,3,"565,4",65.7,57.6,08-11-2025,Szczecin
2,282,34.0,kobieta,eksperymentalna,doktorat,4.0,8,"628,3","70,8",71.0,06-11-2025,Krakow
3,387,20.0,kobieta,kontrolna,licencjat,7.3,5,"562,2","83,0",64.7,31-10-2025,Lublin
4,262,33.0,kobieta,eksperymentalna,magister,8.2,1,630.5,82.9,"91,6",2025-10-19,Gdansk

In [114]:
trials_df.head()

   trial_id  participant_id condition difficulty correct  rt_ms confidence_1_5
0         1             399         b       easy       1  458.0              1
1         2              19         a       easy       1  414.1              5
2         3             993         c     medium     tak  405,3              3
3         4             160         b       easy     tak  479.8              1
4         5             650         c       hard       1  731.2              4

In [142]:
# tutaj dodaj swój kod
trials_df[["condition", "difficulty"]] = trials_df[["condition", "difficulty"]].apply(lambda x: x.str.lower().str.strip().replace(replacement_map))

print (trials_df["condition"].value_counts())
print (trials_df["difficulty"].value_counts())

condition
a    1022
c    1004
b     974
Name: count, dtype: int64
difficulty
medium    1017
hard       997
easy       986
Name: count, dtype: int64

In [116]:
trials_df

,trial_id,participant_id,condition,difficulty,correct,rt_ms,confidence_1_5
0,1,399,b,easy,1,458.0,1
1,2,19,a,easy,1,414.1,5
2,3,993,c,medium,tak,"405,3",3
3,4,160,b,easy,tak,479.8,1
4,5,650,c,hard,1,731.2,4
...,...,...,...,...,...,...,...
2995,2996,150,c,hard,tak,711.9,2
2996,2997,876,c,easy,tak,526.0,2
2997,2998,411,c,hard,0,684.7,4
2998,2999,730,a,medium,tak,"677,7",4
2999,3000,165,b,medium,tak,"664,5",3

## <span style="color:#0f766e; font-weight:700;">Zadanie 3</span>

Napraw typy danych: kolumny liczbowe, daty oraz pola z przecinkiem dziesiętnym.

Wymagane biblioteki:
- `pandas`
- `numpy`

Wymagane funkcje/parametry:
- `Series.str.replace()`
- `pd.to_numeric()`
- `pd.to_datetime()`
- parametry `errors`, `dayfirst`
- `DataFrame.dtypes`

In [144]:
display(city_df.head(3))
display(participants_df.head(3))
display(trials_df.head(3))

       city       region  population_k
0  Warszawa  mazowieckie          1861
1    Krakow  malopolskie           806
2    Gdansk    pomorskie           487

   participant_id   age     gender            group education sleep_hours stress_level reaction_time_ms memory_score attention_score session_date      city
0             707  30.0    kobieta  eksperymentalna  magister         7.5            8            597.3          NaN            59,4   2025-11-10    Gdansk
1             975  19.0  mężczyzna        kontrolna  magister         5.6            3            565,4         65.7            57.6   08-11-2025  Szczecin
2             282  34.0    kobieta  eksperymentalna  doktorat         4.0            8            628,3         70,8            71.0   06-11-2025    Krakow

   trial_id  participant_id condition difficulty correct  rt_ms confidence_1_5
0         1             399         b       easy       1  458.0              1
1         2              19         a       easy       1  414.1              5
2         3             993         c     medium     tak  405,3              3

In [145]:
display(city_df.dtypes)
display(participants_df.dtypes)
display(trials_df.dtypes)

city            object
region          object
population_k     int64
dtype: object

participant_id        int64
age                 float64
gender               object
group                object
education            object
sleep_hours          object
stress_level         object
reaction_time_ms     object
memory_score         object
attention_score      object
session_date         object
city                 object
dtype: object

trial_id           int64
participant_id     int64
condition         object
difficulty        object
correct           object
rt_ms             object
confidence_1_5    object
dtype: object

In [ ]:
dfs = {
    "participants_df": participants_df,
    "trials_df": trials_df,
    "city_df": city_df
}

typy_kolumn = {
    
    "participants_df": 
    {
        "numeric": ["sleep_hours", "stress_level", "reaction_time_ms", "memory_score", "attention_score"],
        "date": ["session_date"],
        "comma": ["reaction_time_ms", "memory_score", "attention_score"]
    },


    "trials_df": 
    {
        "numeric": ["rt_ms", "confidence_1_5"],
        "date": [],
        "comma": ["rt_ms"]
    },


    "city_df": 
    {
        "numeric": [],
        "date": [],
        "comma": []
    }
}

for nazwa_df, df in dfs.items():
    
    for col in typy_kolumn[nazwa_df]["comma"]:
        df[col] = df[col].astype(str).str.replace(",", ".")

    for col in typy_kolumn[nazwa_df]["numeric"]:
        df[col] = pd.to_numeric(df[col], errors="coerce")

    for col in typy_kolumn[nazwa_df]["date"]:
        df[col] = pd.to_datetime(df[col], errors="coerce")

In [155]:
display(city_df.dtypes)
display(participants_df.dtypes)
display(trials_df.dtypes)

city            object
region          object
population_k     int64
dtype: object

participant_id               int64
age                        float64
gender                      object
group                       object
education                   object
sleep_hours                float64
stress_level               float64
reaction_time_ms           float64
memory_score               float64
attention_score            float64
session_date        datetime64[ns]
city                        object
dtype: object

trial_id            int64
participant_id      int64
condition          object
difficulty         object
correct            object
rt_ms             float64
confidence_1_5    float64
dtype: object

## <span style="color:#0f766e; font-weight:700;">Zadanie 4</span>

Obsłuż braki danych (`NA`, `brak`, `.`, `999`, puste pola`) i przygotuj tabelę braków przed oraz po czyszczeniu.

Wymagane biblioteki:
- `pandas`
- `numpy`

Wymagane funkcje/parametry:
- `DataFrame.replace()`
- `DataFrame.isna()`
- `DataFrame.sum()`
- `DataFrame.dropna()` / `DataFrame.fillna()`

In [162]:
# tutaj dodaj swój kod
display(city_df)
display(participants_df)
display(trials_df)

       city              region  population_k
0  Warszawa         mazowieckie          1861
1    Krakow         malopolskie           806
2    Gdansk           pomorskie           487
3   Wroclaw        dolnoslaskie           674
4    Poznan       wielkopolskie           545
5      Lodz             lodzkie           652
6    Lublin           lubelskie           339
7  Szczecin  zachodniopomorskie           391

      participant_id   age     gender            group  education  sleep_hours  stress_level  reaction_time_ms  memory_score  attention_score session_date      city
0                707  30.0    kobieta  eksperymentalna   magister          7.5           8.0             597.3           NaN             59.4   2025-10-11    Gdansk
1                975  19.0  mężczyzna        kontrolna   magister          5.6           3.0             565.4          65.7             57.6          NaT  Szczecin
2                282  34.0    kobieta  eksperymentalna   doktorat          4.0           8.0             628.3          70.8             71.0          NaT    Krakow
3                387  20.0    kobieta        kontrolna  licencjat          7.3           5.0             562.2          83.0             64.7          NaT    Lublin
4                262  33.0    kobieta  eksperymentalna   magister          8.2           1.0             630.5          82.9             91.6          NaT    Gdansk
...              ...   ...        ...              ...        ...          ...           ...               ...           ...              ...          ...       ...
1025             129  26.0  mężczyzna  eksperymentalna  licencjat          6.9           4.0             469.5          78.5             69.0          NaT   Wroclaw
1026             910  29.0  mężczyzna  eksperymentalna  licencjat          4.6           3.0             645.2          54.4             75.4          NaT    Poznan
1027             133  30.0    kobieta  eksperymentalna    średnie          4.1           NaN             353.9          42.1             27.1          NaT    Poznan
1028             364  45.0    kobieta        kontrolna    średnie          5.0          10.0             429.1          44.5             61.9          NaT    Krakow
1029             641  18.0    kobieta        kontrolna  licencjat          6.3           1.0             616.5          56.7             53.2          NaT  Szczecin

[1030 rows x 12 columns]

      trial_id  participant_id condition difficulty correct  rt_ms  confidence_1_5
0            1             399         b       easy       1  458.0             1.0
1            2              19         a       easy       1  414.1             5.0
2            3             993         c     medium     tak  405.3             3.0
3            4             160         b       easy     tak  479.8             1.0
4            5             650         c       hard       1  731.2             4.0
...        ...             ...       ...        ...     ...    ...             ...
2995      2996             150         c       hard     tak  711.9             2.0
2996      2997             876         c       easy     tak  526.0             2.0
2997      2998             411         c       hard       0  684.7             4.0
2998      2999             730         a     medium     tak  677.7             4.0
2999      3000             165         b     medium     tak  664.5             3.0

[3000 rows x 7 columns]

In [161]:
display(city_df.isna().sum())
display(participants_df.isna().sum())
display(trials_df.isna().sum())

city            0
region          0
population_k    0
dtype: int64

participant_id        0
age                   9
gender                0
group                 0
education             0
sleep_hours          28
stress_level         29
reaction_time_ms      0
memory_score         43
attention_score       0
session_date        882
city                  0
dtype: int64

trial_id            0
participant_id      0
condition           0
difficulty          0
correct             0
rt_ms               0
confidence_1_5    284
dtype: int64

In [175]:
slownik_brakow={"session_date":"NaT",
                "age":"Nan"
                }

participants_df[participants_df[["stress_level","sleep_hours", "age"]].isna().any(axis=1)]

      participant_id   age     gender            group  education  sleep_hours  stress_level  reaction_time_ms  memory_score  attention_score session_date      city
6                263  22.0  mężczyzna  eksperymentalna  licencjat          NaN          10.0             646.6          54.5             42.3          NaT  Warszawa
15               372  31.0  mężczyzna  eksperymentalna   magister          7.3           NaN             659.7          70.7             92.8          NaT  Warszawa
27               208  19.0  mężczyzna        kontrolna    średnie          4.7           NaN             463.6          51.4             73.6          NaT   Wroclaw
38               549  23.0  mężczyzna        kontrolna   magister          NaN           7.0             590.0          78.1             55.8          NaT    Lublin
45               277  39.0  mężczyzna  eksperymentalna  licencjat          NaN           6.0             549.0          79.4             40.4          NaT    Poznan
...              ...   ...        ...              ...        ...          ...           ...               ...           ...              ...          ...       ...
979              425   NaN    kobieta        kontrolna   doktorat          8.2           5.0             421.6          58.8             56.7          NaT      Lodz
992              540  41.0  mężczyzna  eksperymentalna   magister          NaN          10.0             302.3          80.3             44.7          NaT      Lodz
997              652   NaN    kobieta  eksperymentalna  licencjat          6.3           6.0             578.9          37.2             59.6          NaT  Szczecin
1013             993  21.0  mężczyzna        kontrolna   doktorat          5.4           NaN             401.6          62.2             74.8          NaT   Wroclaw
1027             133  30.0    kobieta  eksperymentalna    średnie          4.1           NaN             353.9          42.1             27.1          NaT    Poznan

[66 rows x 12 columns]

## <span style="color:#0f766e; font-weight:700;">Zadanie 5</span>

Usuń duplikaty w `participants_dirty.csv` i policz ile rekordów usunięto.

Wymagane biblioteki:
- `pandas`

Wymagane funkcje/parametry:
- `DataFrame.duplicated()`
- `DataFrame.drop_duplicates()`
- parametr `subset`

In [193]:
# tutaj dodaj swój kod
display(participants_df[participants_df.duplicated()])
display(participants_df[participants_df["participant_id"].isin([29, 78, 436])])

      participant_id   age     gender            group  education  sleep_hours  stress_level  reaction_time_ms  memory_score  attention_score session_date      city
243               29  37.0  mężczyzna        kontrolna   magister          7.9           1.0             629.8          61.8             85.1          NaT    Gdansk
317               78  36.0  mężczyzna        kontrolna  licencjat          8.2           4.0             452.1          57.9             61.6          NaT    Poznan
341              436  38.0    kobieta  eksperymentalna  licencjat          8.9           6.0             708.3          65.2             88.3          NaT  Warszawa
366              547  33.0    kobieta        kontrolna    średnie          7.3           6.0             763.6           NaN             74.0          NaT  Warszawa
436              462  24.0  mężczyzna  eksperymentalna   doktorat          4.9           1.0             416.0          51.3             36.9          NaT    Poznan
486              191  41.0  mężczyzna        kontrolna   magister          4.9           NaN             366.3          57.9             63.7   2025-01-10    Gdansk
521              778  22.0    kobieta        kontrolna   doktorat          4.2           3.0            1410.2          67.0             58.2   2025-07-10  Szczecin
529              240  21.0    kobieta  eksperymentalna   doktorat          8.6           5.0             639.1          58.5             53.0          NaT    Gdansk
549              753  35.0    kobieta        kontrolna   magister          5.8           2.0             432.8          81.0             62.4          NaT    Krakow
583              492  23.0    kobieta  eksperymentalna   magister          7.7           3.0             547.5          61.2             50.5          NaT      Lodz
672              517  18.0  mężczyzna        kontrolna    średnie          7.2           2.0             580.3          56.6             36.7   2025-05-10    Gdansk
697              268  26.0  mężczyzna        kontrolna  licencjat          9.1           6.0             743.7          52.0             80.5          NaT  Szczecin
706              324  30.0    kobieta  eksperymentalna   magister          7.2           NaN             394.4          57.4             50.8          NaT  Szczecin
738              161  19.0  mężczyzna        kontrolna    średnie          5.1           2.0            1886.0          72.5             81.3          NaT    Krakow
757              275  25.0    kobieta        kontrolna   doktorat          7.5           9.0             417.5          66.6             69.2          NaT  Warszawa
792               15  45.0    kobieta  eksperymentalna   doktorat          6.2           NaN             496.5          52.7             64.0          NaT    Poznan
826              408  33.0  mężczyzna  eksperymentalna  licencjat          8.6          10.0             548.8          45.5             70.8          NaT  Warszawa
832              254  45.0  mężczyzna  eksperymentalna  licencjat          8.1          10.0             558.5          62.5             65.6          NaT    Lublin
836              460  40.0  mężczyzna  eksperymentalna  licencjat          4.5          10.0             484.0          48.0             55.4          NaT  Szczecin
851              479  38.0    kobieta  eksperymentalna    średnie          7.7           7.0             538.8          65.0             75.7          NaT      Lodz
864              219  22.0  mężczyzna  eksperymentalna  licencjat          4.0           3.0             711.5          56.3             58.0          NaT    Krakow
880             1000  39.0  mężczyzna        kontrolna   magister          6.4           7.0             522.0          74.7             58.9          NaT      Lodz
886              326  19.0    kobieta        kontrolna   doktorat          8.8           3.0             468.0          64.1             70.6          NaT    Poznan
914              556  38.0    kobieta  eksperymentalna  licencjat          7.2           3.0             524.9          60.6             76.7          NaT  Warszawa
927               90  45.0  mężczyzna        kontrolna  licencjat          4.5           3.0             495.1          68.1             48.9          NaT   Wroclaw
942              620  45.0    kobieta        kontrolna   magister          5.4           3.0             737.9          58.3             66.8          NaT    Poznan
948              991  33.0    kobieta        kontrolna  licencjat          5.6          10.0             536.9          78.4             61.8          NaT    Krakow
1013             993  21.0  mężczyzna        kontrolna   doktorat          5.4           NaN             401.6          62.2             74.8          NaT   Wroclaw
1021             710  40.0  mężczyzna        kontrolna  licencjat          9.1          10.0             643.7          60.0             78.5          NaT    Gdansk
1027             133  30.0    kobieta  eksperymentalna    średnie          4.1           NaN             353.9          42.1             27.1          NaT    Poznan

     participant_id   age     gender            group  education  sleep_hours  stress_level  reaction_time_ms  memory_score  attention_score session_date      city
69               29  37.0  mężczyzna        kontrolna   magister          7.9           1.0             629.8          61.8             85.1          NaT    Gdansk
243              29  37.0  mężczyzna        kontrolna   magister          7.9           1.0             629.8          61.8             85.1          NaT    Gdansk
274             436  38.0    kobieta  eksperymentalna  licencjat          8.9           6.0             708.3          65.2             88.3          NaT  Warszawa
312              78  36.0  mężczyzna        kontrolna  licencjat          8.2           4.0             452.1          57.9             61.6          NaT    Poznan
317              78  36.0  mężczyzna        kontrolna  licencjat          8.2           4.0             452.1          57.9             61.6          NaT    Poznan
341             436  38.0    kobieta  eksperymentalna  licencjat          8.9           6.0             708.3          65.2             88.3          NaT  Warszawa

In [195]:
participants_df = participants_df.drop_duplicates()
display(participants_df[participants_df.duplicated()])

Empty DataFrame
Columns: [participant_id, age, gender, group, education, sleep_hours, stress_level, reaction_time_ms, memory_score, attention_score, session_date, city]
Index: []

## <span style="color:#0f766e; font-weight:700;">Zadanie 6</span>

Zdefiniuj reguły jakości danych (np. zakresy dla `age`, `sleep_hours`, `reaction_time_ms`, `memory_score`) i odfiltruj obserwacje spoza zakresu.

Wymagane biblioteki:
- `pandas`
- `numpy`

Wymagane funkcje/parametry:
- filtrowanie logiczne
- `DataFrame.between()`
- operatory `&`, `|`, `~`

In [ ]:
age = participants_df[(participants_df["sleep_hours"] > 5) | (participants_df["sleep_hours"] < 12)]

      participant_id   age     gender            group  education  sleep_hours  stress_level  reaction_time_ms  memory_score  attention_score session_date      city
0                707  30.0    kobieta  eksperymentalna   magister          7.5           8.0             597.3           NaN             59.4   2025-10-11    Gdansk
1                975  19.0  mężczyzna        kontrolna   magister          5.6           3.0             565.4          65.7             57.6          NaT  Szczecin
2                282  34.0    kobieta  eksperymentalna   doktorat          4.0           8.0             628.3          70.8             71.0          NaT    Krakow
3                387  20.0    kobieta        kontrolna  licencjat          7.3           5.0             562.2          83.0             64.7          NaT    Lublin
4                262  33.0    kobieta  eksperymentalna   magister          8.2           1.0             630.5          82.9             91.6          NaT    Gdansk
...              ...   ...        ...              ...        ...          ...           ...               ...           ...              ...          ...       ...
1024             675  34.0  mężczyzna  eksperymentalna   magister          8.3           5.0             455.7          93.7             69.2          NaT    Poznan
1025             129  26.0  mężczyzna  eksperymentalna  licencjat          6.9           4.0             469.5          78.5             69.0          NaT   Wroclaw
1026             910  29.0  mężczyzna  eksperymentalna  licencjat          4.6           3.0             645.2          54.4             75.4          NaT    Poznan
1028             364  45.0    kobieta        kontrolna    średnie          5.0          10.0             429.1          44.5             61.9          NaT    Krakow
1029             641  18.0    kobieta        kontrolna  licencjat          6.3           1.0             616.5          56.7             53.2          NaT  Szczecin

[972 rows x 12 columns]

In [218]:
participants_df1 = participants_df
[
    participants_df[
    (participants_df["age"] >= 6) & (participants_df["age"] <= 70) &
    (participants_df["sleep_hours"] >= 5) & (participants_df["sleep_hours"] <= 12) &
    (participants_df["reaction_time_ms"] >= 100) & (participants_df["reaction_time_ms"] <= 2000) &
    (participants_df["memory_score"] >= 30) & (participants_df["memory_score"] <= 100)
    ]
]

[      participant_id   age     gender            group  education  sleep_hours  stress_level  reaction_time_ms  memory_score  attention_score session_date      city
 1                975  19.0  mężczyzna        kontrolna   magister          5.6           3.0             565.4          65.7             57.6          NaT  Szczecin
 3                387  20.0    kobieta        kontrolna  licencjat          7.3           5.0             562.2          83.0             64.7          NaT    Lublin
 4                262  33.0    kobieta  eksperymentalna   magister          8.2           1.0             630.5          82.9             91.6          NaT    Gdansk
 5                811  32.0    kobieta  eksperymentalna  licencjat          7.4           9.0             577.6          70.4             63.0   2025-04-11    Gdansk
 7                697  27.0  mężczyzna        kontrolna   magister          7.1           7.0             586.1          63.7             70.4          NaT    Krakow
 ...              ...   ...        ...              ...        ...          ...           ...               ...           ...              ...          ...       ...
 1022             565  43.0    kobieta  eksperymentalna   magister          8.8          10.0             538.5          59.1             52.6          NaT    Lublin
 1024             675  34.0  mężczyzna  eksperymentalna   magister          8.3           5.0             455.7          93.7             69.2          NaT    Poznan
 1025             129  26.0  mężczyzna  eksperymentalna  licencjat          6.9           4.0             469.5          78.5             69.0          NaT   Wroclaw
 1028             364  45.0    kobieta        kontrolna    średnie          5.0          10.0             429.1          44.5             61.9          NaT    Krakow
 1029             641  18.0    kobieta        kontrolna  licencjat          6.3           1.0             616.5          56.7             53.2          NaT  Szczecin

 [759 rows x 12 columns]]